.TH man 1 "06 January 2023" "0.1.0" "rooibos man page"

.SH NAME
rooibos \- A modern window manager for X11

.SH SYNOPSIS
rooibos [OPTION]

.SH DESCRIPTION
Rooibos is a modern window manager written in C with the Xlib library, the low-level library of the X Window System.
Rooibos is written with the Xlib library because it is a low-level and lightweight library, and to give the best user experience.

.SH OPTIONS
Options are :
.TP
\fBcache-init\fR	Create the cache database
.TP
\fBcache-update\fR	Update the cache database

To launch Rooibos, you have to execute this command : startx rooibos

Splash logo and wallpaper can be modified. You just have to copy these files in $HOME/.rooibos/.
Splash logo must be in .svg format in $HOME/.rooibos/logo.svg.
Wallpaper must be in .png format in $HOME/.rooibos/wallpaper.png.

.SH AUTHOR
Written by François Basset
